on:
    push:
      branches:
      - cli-updates

jobs:
    pull-request:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Open PR
          uses: repo-sync/pull-request@v2
          with:
            destination_branch: "main"
            github_token: ${{ secrets.GITHUB_TOKEN }}
            pr_title: "CLI Doc Generation: ${{ github.ref_name }}"